adding 'pure/test/fntest_pure.lua'
gvs-rs/pubnub-lua pull request #1
Opened 2019-06-25 17:35 UTC by Petar-Saric

2019-06-27 11:29 UTC, sveljko requested changes

2019-06-27 11:29 UTC, sveljko commented on pure/test/fntest_pure.lua
> +    --[[ For defferent pubnub objects 'init' tables must be defferent( locations in memory) --]]
d_i_ferrent

2019-06-27 11:29 UTC, sveljko commented on pure/test/fntest_pure.lua
> +        presence = presence
Чланови табеле нису поравнати - ово се често јавља, нема смисла свуда да обележавам, прођи па среди.

Обрати пажњу, често ти се "увуче" ТАБ знак

2019-06-27 11:29 UTC, sveljko commented on pure/test/fntest_pure.lua
> +	                 origin        = origin    -- PUBNUB CLOUD ORIGIN
ови коментари "десно" ничему не служе

2019-06-29 11:04 UTC, sveljko requested changes

2019-06-29 11:04 UTC, sveljko commented on pure/examples/example-subscribe/BinDecHex.lua
> +--]]
Овај коментар треба избацити (код стоји у историји, ако неком затреба)

2019-06-29 11:04 UTC, sveljko commented on pure/test/fntest_pure.lua
> +local params = {...}
хм, а шта ће ти витичасте заграде? Нешто "љепше" понашање добијеш са:

    local params = ...

Наиме, пробај `print(params)` са и без витичастих заграда па ћеш да видиш разлику

2019-06-29 11:04 UTC, sveljko commented on pure/test/fntest_pure.lua
> +local origin = getenv_ex("PUBNUB_ORIGIN", (#params > 2) and params[3] or "pubsub.pubnub.com")
ps.pndsn.com

2019-06-29 11:04 UTC, sveljko commented on pure/test/fntest_pure.lua
> +function __LINE__() return debug.getinfo(2, 'l').currentline end
Збуњујуће је да имаш и `ФИЛЕ` и `__ФИЛЕ__` (разликују се само у подвлакама).. Боље нека ово буде `гет_филе` или тако нешто

2019-06-29 11:04 UTC, sveljko commented on pure/test/fntest_pure.lua
> +            table.remove(expected_messages, k)
начелно, мењање неке структуре података док се "обилази" је проблем. Не знам тачко да ли је то проблем за Луа табеле и `фор ин` обилазак, али, увек "пали лампицу за аларм". Стога, или:

1. направиш локалну копију која се обилази (а мењаш изворну табелу)
2. ставиш коментар "мењање табеле за време обиласка је прихватљиво у Луи"

Ако успорење због прављења локалне копије није проблем, ја сам увек пре за решење које се _не_ ослања на коментаре. Коментари буђају.

2019-06-29 11:04 UTC, sveljko commented on pure/test/fntest_pure.lua
> +local function received_expected_messages( __file__, __line__ )
чини се да ја ово `рецеивед_алл_еџпецтед_мессагес`

2019-06-29 11:04 UTC, sveljko commented on pure/test/fntest_pure.lua
> +                                    __file__,
ови `__филе__` су још додатно збуњујући (спрам `ФИЛЕ` и `__ФИЛЕ__`)… назови их нешто попут `субс_филе` или тако нешто

2019-06-29 11:04 UTC, sveljko commented on pure/test/fntest_pure.lua
> +run_tests()
Овде би требало позвати `ос.еџит()` са "налазом" (0 ако су сви тестови "прошли", а неки други број ако неки није). Рецимо `ос.еџит(фаилед_тестс)`

2019-06-29 11:04 UTC, sveljko commented on pure/test/fntest_pure.lua
> +local failed_tests = 0
све ове "статичке" променљиве бих ја стрпао у једну табелу и онда је "шетао около". Тако сутра можемо ову "тест подршку" та ставимо у посебан Луа "модул" и користимо га из различитих Луа тестова.

2019-06-29 22:27 UTC, Petar-Saric commented on pure/test/fntest_pure.lua
> +local params = {...}
Ако се витичасте заграде изоставе фнтест ће да се заустави(заглави) тражећи дужину табеле `парамс` која је `нил`, ако се покрене без параметара : луа фнтест_пуре.луа.

2019-06-30 07:28 UTC, Petar-Saric commented on pure/test/fntest_pure.lua
> +local params = {...}
Ако се витичасте заграде изоставе фнтест ће да се заустави(заглави) тражећи дужину табеле `парамс` која је `нил`, ако се покрене без параметара : луа фнтест_пуре.луа.

2019-06-30 08:21 UTC, sveljko approved these changes

2019-06-30 08:23 UTC, merged