signal(), subscribe_v2(), publish() with metadata and 'fntest_pure'
gvs-rs/pubnub-lua pull request #5
Opened 2019-10-09 11:29 UTC by Petar-Saric

2019-10-09 11:43 UTC, sveljko requested changes

2019-10-09 11:43 UTC, sveljko commented on pure/test/fntest_pure.lua
> +       if not didnt_receive_any_of_expected_messages( t_ctx,
ово је збуњујуће "нот диднт`... уместо тога, нешто попут "нот рисивд_ени_експектид_месиџ(…)"

2019-10-09 11:43 UTC, sveljko commented on pure/test/pubnub.lua
> +    MESSAGE_TYPE_ACTION = 3
треба да буду `лоцал`

2019-10-09 15:04 UTC, Petar-Saric commented on pure/test/pubnub.lua
> +    MESSAGE_TYPE_ACTION = 3
Ako su 'local', ne vide se u testovima.

2019-10-09 20:13 UTC, sveljko commented on pure/test/pubnub.lua
> +    MESSAGE_TYPE_ACTION = 3
Да, извињавам се, нисам био доречен. У Луи не постоји `цонст` (прецизније, постојаће у 5.4, али засад не постоји). Дакле, ако се направи овако, онда свако може у свом коду да промени ове "константе" и онда имамо "белај". :)

Да би се то избегло, ставимо да буду `лоцал` а омогућимо да се читају са неке три помоћне функције ( попут `фунцтион мессаге_тупе_публисхед() ретурн МЕССАГЕ_ТУПЕ_ПУБЛИСХЕД;`). 

У ствари треба направити и помоћне `ис_мессаге_публисхед(мсг)` и сл., које примају в2 поруку и враћају да ли је "објављена" односно да ли је "сигнал" итд. То ће кориснику бити лакше и лепше за употребу.

2019-10-10 08:35 UTC, sveljko approved these changes

2019-10-10 08:35 UTC, merged